---
name: Workflow A
permissions: { }

on:
  push:
    # branches: [ main ]
    paths:
      - '.github/workflows/a.yml'
      - 'a/**'

jobs:
  a:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -lsh
