---
name: Workflow B
permissions: { }

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/b.yml'
      - 'b/**'

jobs:
  b:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -lsh
