---
name: Workflow B
permissions: { }

on:
  push:
    # branches: [ main ]
    paths:
      - 'b/**'
      - '!b/README.md'
      - '.github/workflows/b.yml'

jobs:
  b:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -lsh
